name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout código fonte
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Instalar dependências e rodar testes
      - name: Build with Maven
        run: |
          ./mvnw clean package
          ./mvnw test

  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/url-shortener:latest .
          docker push your-dockerhub-username/url-shortener:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f infrastructure/kubernetes/deployment.yaml
          kubectl apply -f infrastructure/kubernetes/service.yaml
          kubectl apply -f infrastructure/kubernetes/ingress.yaml
